//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCategoriesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerCategoriesTbl()
        {
            this.CustomerTbls = new HashSet<CustomerTbl>();
        }
    
        public long CustomerCategoriesID { get; set; }
        public string CustomerCategoriesName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTbl> CustomerTbls { get; set; }
    }
}
