//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTbl
    {
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string PrimaryContact { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<long> CustomerCategoriesID { get; set; }
    
        public virtual CustomerCategoriesTbl CustomerCategoriesTbl { get; set; }
    }
}
